using Lab1.Domain.Users;

namespace Lab1.Domain
{
    internal class Account()
    {
        public int IdNumber { get; set; } // generated by database
        public required Bank Bank { get; set; }
        public decimal Amount { get; set; }
        public bool IsActive { get; set; }

        public override string ToString()
        {
            return $"Account ID: {IdNumber.ToString()}, " +
                   $"Bank: {Bank.Name} (ID: {Bank.Id}), " +
                   $"Amount: {Amount:C}, " +
                   $"IsActive: {IsActive}";
        }
    }
}
