

using Lab1.Domain.BankServices;

namespace Lab1.Domain
{
    public enum CompanyType
    {
        IndividualEntrepreneur,
        LimitedLiabilityCompany,
        ClosedJointStockCompany
    }

    internal class Company
    {
        public int Id { get; set; } // generated by dadabase
        public required CompanyType CompanyType { get; set; }
        public required string Name { get; set; }
        public required Account Account { get; set; }
        public required string Address { get; set; }
        public SalaryProject? SalaryProject { get; set; } = null;

        public override string ToString()
        {
            return $"Company ID: {Id}, " +
                   $"Type: {CompanyType}, " +
                   $"Name: {Name}, " +
                   $"Address: {Address}, " +
                   $"Account: {Account.ToString()}, " +
                   $"SalaryProject: {SalaryProject?.ToString() ?? "N / A"}";
        }
    }
}
