

namespace Lab1.Domain.BankServices
{
    internal class SalaryProject
    {
        public int IdNumber { get; set; } // generated by database
        public int BankId { get; set; }
        public required string CompanyName {  get; set; }
        public bool IsCompleted { get; set; } = false;
        public Dictionary<Account, decimal> Salaries { get; set; } = new Dictionary<Account, decimal>();
        public override string ToString()
        {
            var salariesString = string.Join(", ", Salaries.Select(kvp => $"{kvp.Key.IdNumber}: {kvp.Value:C}"));

            return $"SalaryProject ID: {IdNumber}, " +
                   $"Bank ID: {BankId}, " +
                   $"Company Name: {CompanyName}, " +
                   $"Is Completed: {IsCompleted}, " +
                   $"Salaries: [{salariesString}]";
        }
    }
}
